### ISSUE TITLE
Review clingen-static-resources Branding Branch

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-static-resources#2]
Hello @larrybabb @cbizon @nafisakhandaker @bpow @tnavatar !I wrapped up the UI/UX updates for clingen-static-resources in a branch (https://github.com/clingen-data-model/clingen-static-resources/tree/BrandingQ42017) Take a look and let me know if you have any ideas/issues. 

Essentially I took what I needed from data-model-docs and brought them in here... I think that is correct. (-:

**Comment by nafisakhandaker** [comment]
It make sense as long as there is one copy of static resources. You can put
it locally in clingen-data-model folder. That is even better. But I am only
concern when there are multiple copy of same resource. It really doesn't
make sense.

*Nafisa Khandaker*
Email: nafkhan@gmail.com Cell: 617-501-7745 <6175017745>

**Comment by sgoehringer** [comment]
I 100% agree about the deal copies but I wasn’t 100% sure how to test things locally without adding them to the main domain because that is where they are referenced. I am sure we can find a solution to this when things settle down.

**Comment by sgoehringer** [comment]
Closing this for now because somewhat covered under issue https://github.com/clingen-data-model/data-model-docs/issues/10 That may now be in the wrong place... anyway, just cleaning this up.
